@isset($item['data']['authorization'])
    @switch($item['data']['authorization'])
    @case('guest')
        @guest
            @include('partials.link')
        @endguest
    @break
    @case('auth')
        @auth
            @include('partials.link')
        @endauth
        @break
        @default
        @include('partials.link')
@endswitch
@else
    @include('partials.link')
@endisset

